title: Picklecillo Dev
description: Mis notas
author: Pickle Cillo
github: https://github.com/picklecillo
about: Codeo :)
disqus_shortname: picklecillodev
google_analytics: UA-63740907-3

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/picklecillo"

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://picklecillo.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
